-- 거래 원장 테이블
DROP TABLE IF EXISTS TRADE;
CREATE TABLE TRADE (TRD_DT VARCHAR, ACCT_NO VARCHAR, TRD_NO VARCHAR, AMT INT, FEES INT, CANCEL BOOLEAN);

-- 계좌 정보 테이블
DROP TABLE IF EXISTS BANK;
CREATE TABLE BANK (ACCT_NO VARCHAR PRIMARY KEY, ACCT_NM VARCHAR, BRANCH_CD VARCHAR);

-- 가맹점 테이블
DROP TABLE IF EXISTS BRANCH;
CREATE TABLE BRANCH (BRANCH_CD VARCHAR, BRANCH_NM VARCHAR);
